language: java
env:
  matrix:
  - PLATFORM=railo41 TARGET=test-ci
  - PLATFORM=railo42beta TARGET=test-ci
  - PLATFORM=railo42beta TARGET=build

install: ant -f build/build.xml -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM install-ci-deps
script: ant -f build/build.xml -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM -Dbranch=$TRAVIS_BRANCH -Dtag=$TRAVIS_TAG $TARGET

deploy:
  provider: s3
  access_key_id: AKIAJ3PTU73IHOOZV3LQ
  secret_access_key:
    secure: WMBNULr8RwOLrcIpOkjCgKjo4492ITvkdNAnZRLKhxRqrcRGpF/KwlCGm+Lhmdo4gc0Kv+6Cuou/7dx2eH/0Updg+qDgpbB5akmjxcXCfYTvc6v5n73FZ/sJBjnVpYSBSovn6OcbLcJF+Smqld0czBDtqobnBuwXvyUa/egA+A4=
  bucket: downloads.presidecms.com
  local-dir: build/artifacts
  upload-dir: sticker
  skip_cleanup: true
  on:
    repo: pixl8/sticker
    condition: "$TARGET = build"
    all_branches: true
